#!/bin/bash
# Code generated by Gemini 3; checked by Donnell.

# 0. Store input params in more readable vars
SITE_TITLE="$1"
INPUT_FILE="$2"
JS_FILE="$3"
CSS_FILE="$4"

# 1. Make sure all three files were provided
if [[ -z "$1" || -z "$2" || -z "$3" || -z "$4" ]]; then
    echo "Error: Missing arguments."
    echo "Usage: ./md_to_html.sh <title for site> <example.md> <script_file.js> <styles_file.css>"
    echo "NOTE: when you run this script, make sure your current working \
    directory is the one that you will serve your MD / HTML file from."
    exit 1
fi

# 2. Make sure all files exist
for file in "$INPUT_FILE" "$JS_FILE" "$CSS_FILE"; do
    if [ ! -f "$file" ]; then
        echo "Error: File '$file' not found."
        exit 1
    fi
done

# 3. Read the file content into a variable
# We use a subshell to capture the file contents
MD_CONTENT=$(cat "$INPUT_FILE")

# 4. Turn <trap> tags into valid HTML. Perl used for multi-line replacements.
# -0777: Slurp mode (reads the whole file as one string)
# -pe: Execute the script and print the result
# /gs: 'g' is global, 's' allows '.' to match newlines (the "Single-line" flag)
MD_CONTENT=$(echo "$MD_CONTENT" | perl -0777 -pe '
    s/<trap type="invis">(.*?)<\/trap>/<span class="trap-invis">$1<\/span>/gs;
    s/<trap type="hotswap" replacement="(.*?)">(.*?)<\/trap>/<span class="trap-hotswap" data-replacement="$1">$2<\/span>/gs;
')

# 5. Prepare output filename and assets
BASENAME="${INPUT_FILE%.*}"
OUTPUT_FILE="${BASENAME}.html"

echo "Processing $INPUT_FILE..."

# 6. Pipe the variable into Pandoc
# Note the '-' at the end of the command—it tells Pandoc to read from STDIN
echo "$MD_CONTENT" | pandoc -s \
  -f markdown \
  --mathjax \
  -c $CSS_FILE \
  -M pagetitle="$SITE_TITLE" \
  -H <(echo "<script src=\"${JS_FILE}\"></script>") \
  --syntax-highlighting=pygments \
  -o "$OUTPUT_FILE" -

# 7. Success check
if [ $? -eq 0 ]; then
    echo "Successfully generated: $OUTPUT_FILE"
else
    echo "Error: Pandoc conversion failed."
    exit 1
fi
