#!/bin/bash
# Code generated by Gemini 3; checked by Donnell.

# Make sure input file was provided
if [ $# -eq 0 ]; then
    echo "usage: $0 <input_file> [site_title [js_file [css_file]]]"
    echo
    echo "defaults:"
    echo "  site_title: text after first '# ' in input_file"
    echo "    e.g. \"# HW: Stuff and Things\" -> \"HW: Stuff and Things\""
    echo "  js_file: ../global/index.js"
    echo "  css_file: ../global/md_styles.css"
    echo
    echo "when you run this script, make sure your current working directory is the one"
    echo "from which you will serve your HTML file."
    exit 1
fi

# Store input params in more readable vars
INPUT_FILE="$1"
JS_FILE="${3:-../global/index.js}"
CSS_FILE="${4:-../global/md_styles.css}"

# Make sure all files exist
for file in "$INPUT_FILE" "$JS_FILE" "$CSS_FILE"; do
    if [ ! -f "$file" ]; then
        echo "Error: File '$file' not found."
        exit 1
    fi
done

SITE_TITLE="${2:-$(grep -m 1 '# ' $INPUT_FILE | sed -n -e 's/^# //p')}"

# check that pandoc is installed
if [[ -z "$(which pandoc)" ]]; then
    echo "pandoc is not installed"
    echo "install it before continuing: https://pandoc.org/installing.html"
    echo
    echo "Ubuntu:"
    echo
    echo "wget https://github.com/jgm/pandoc/releases/download/3.9/pandoc-3.9-1-amd64.deb"
    echo "sudo dpkg -i pandoc-3.9-1-amd64.deb"
    echo "rm pandoc-3.9-1-amd64.deb"
    echo
    exit 1
fi

echo "Processing $INPUT_FILE..."

# Pipe the variable into Pandoc
# Note the '-' at the end of the command—it tells Pandoc to read from STDIN
# Turn <trap> tags into valid HTML. Perl used for multi-line replacements.
# -0777: Slurp mode (reads the whole file as one string)
# -pe: Execute the script and print the result
# /gs: 'g' is global, 's' allows '.' to match newlines (the "Single-line" flag)
cat "$INPUT_FILE" |
perl -0777 -pe '
    s/<trap type="invis">(.*?)<\/trap>/<span class="trap-invis">$1<\/span>/gs;
    s/<trap type="hotswap" replacement="(.*?)">(.*?)<\/trap>/<span class="trap-hotswap" data-replacement="$1">$2<\/span>/gs;
    ' |
pandoc -s \
  -f markdown \
  --mathjax \
  -c $CSS_FILE \
  -M pagetitle="$SITE_TITLE" \
  -H <(echo "<script src=\"${JS_FILE}\"></script>") \
  --syntax-highlighting=pygments \
  -o index.html -

# Success check
if [ $? -eq 0 ]; then
    echo "Successfully generated: index.html"
else
    echo "Error: Pandoc conversion failed."
    exit 1
fi
